spring.application.name=investor-analytics

spring.graphql.graphiql.enabled=true

#spring.data.mongodb.uri=mongodb://localhost:27017/investor-analytics
spring.data.mongodb.uri=mongodb+srv://alnocetti:ThisIsATest@cluster0.vmd46u3.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=investor-analytics

app.embeddings.rebuild=false